name: dns
version: 0.1.3
author: terrier989 <terrier989@gmail.com>
homepage: https://github.com/terrier989/dns
description: A package for working with the DNS protocol.

environment:
  sdk: ">=2.4.0 <3.0.0"

executables:
  dns-proxy: dns-proxy

dependencies:
  args: ^1.5.2
  meta: ^1.1.7
  ip: ^0.1.1
  raw: ^0.2.0
  universal_io: '>=0.7.0 <0.9.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.5
